apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: ghcr.io/2023-4400-exp/4402-python-app:28df2f3d9c5c750446a775442cbbccc470695ac4
          name: python-app
          volumeMounts:
            - mountPath: /var/python-app
              name: python-app-data-mount
      volumes:
        - name: python-app-data-mount
          persistentVolumeClaim:
            claimName: python-app-data
